import { DEFAULT_AUTODJ_SETTINGS, DEFAULT_CATEGORIES, RADIO_BRAND, RADIO_NAME, RADIO_SLOGAN, RADIO_STREAMING_TYPES, RADIO_STREAM_URL } from "../config/radioConfig";

export const radioTracksMock = [
  {
    id: "track-1",
    title: "Noite dos Amigos",
    artist: "Banda do Bar",
    album: "Ao Vivo na Resenha",
    category: "Pagode",
    year: 2026,
    bitrate: "96 kbps",
    format: "MP3",
    size: "6.8 MB",
    duration: 218,
    uploadedAt: "2026-06-30T18:20:00.000Z",
    favorite: true,
    cover: "",
  },
  {
    id: "track-2",
    title: "Sertanejo da Galera",
    artist: "Arena Brasil",
    album: "Modao Premium",
    category: "Sertanejo",
    year: 2025,
    bitrate: "96 kbps",
    format: "MP3",
    size: "7.1 MB",
    duration: 241,
    uploadedAt: "2026-06-29T15:10:00.000Z",
    favorite: false,
    cover: "",
  },
  {
    id: "track-3",
    title: "Flashback do Bar",
    artist: "DJ Midnight",
    album: "Classicos",
    category: "Flashback",
    year: 1998,
    bitrate: "96 kbps",
    format: "MP3",
    size: "8.4 MB",
    duration: 266,
    uploadedAt: "2026-06-28T11:42:00.000Z",
    favorite: false,
    cover: "",
  },
  {
    id: "track-4",
    title: "Vinheta Oficial",
    artist: "Radio Bar dos Amigos",
    album: "Identidade",
    category: "Vinhetas",
    year: 2026,
    bitrate: "96 kbps",
    format: "MP3",
    size: "1.2 MB",
    duration: 18,
    uploadedAt: "2026-06-27T09:00:00.000Z",
    favorite: true,
    cover: "",
  },
];

export const radioPlaylistsMock = [
  { id: "playlist-1", name: "Manha Hits", trackIds: ["track-2", "track-1"], shuffle: true, repeat: false },
  { id: "playlist-2", name: "Noite dos Amigos", trackIds: ["track-1", "track-3", "track-4"], shuffle: true, repeat: true },
  { id: "playlist-3", name: "Vinhetas e Comerciais", trackIds: ["track-4"], shuffle: false, repeat: false },
];

export const radioScheduleMock = [
  { id: "schedule-1", day: "Segunda", start: "08:00", end: "10:00", title: "Sertanejo", playlistId: "playlist-1" },
  { id: "schedule-2", day: "Segunda", start: "10:00", end: "12:00", title: "Pagode", playlistId: "playlist-2" },
  { id: "schedule-3", day: "Terca", start: "14:00", end: "18:00", title: "Forro", playlistId: "playlist-1" },
  { id: "schedule-4", day: "Sexta", start: "22:00", end: "23:59", title: "Flashback", playlistId: "playlist-2" },
];

export const radioListenersMock = [
  { id: "listener-1", country: "Brasil", city: "Sao Paulo", system: "Android", browser: "Chrome", device: "Android" },
  { id: "listener-2", country: "Brasil", city: "Rio de Janeiro", system: "iOS", browser: "Safari", device: "iPhone" },
  { id: "listener-3", country: "Brasil", city: "Belo Horizonte", system: "Windows", browser: "Edge", device: "Desktop" },
];

export const radioLogsMock = [
  { id: "log-1", type: "upload", level: "info", message: "Musica importada para a biblioteca.", createdAt: "2026-06-30T18:20:00.000Z" },
  { id: "log-2", type: "streaming", level: "warning", message: "Stream temporario ainda nao configurado.", createdAt: "2026-06-30T18:30:00.000Z" },
  { id: "log-3", type: "autodj", level: "info", message: "AutoDJ pronto para operar com mocks.", createdAt: "2026-06-30T18:40:00.000Z" },
];

export const radioInitialState = {
  config: {
    name: RADIO_NAME,
    slogan: RADIO_SLOGAN,
    streamUrl: RADIO_STREAM_URL,
    statusUrl: "",
    streamingType: RADIO_STREAMING_TYPES.EXTERNAL,
    mountpoint: "",
    port: "",
    password: "",
    codec: "MP3",
    bitrate: "96 kbps",
    format: "audio/mpeg",
    autoReconnect: true,
    autoplay: false,
    defaultVolume: RADIO_BRAND.defaultVolume,
    primaryColor: RADIO_BRAND.primaryColor,
    secondaryColor: RADIO_BRAND.secondaryColor,
    theme: RADIO_BRAND.theme,
    language: RADIO_BRAND.language,
  },
  status: {
    online: false,
    autoDj: true,
    streaming: false,
    currentTrackId: "track-1",
    nextTrackId: "track-2",
    remainingSeconds: 148,
    listenersOnline: 38,
    audiencePeak: 96,
    storageUsedGb: 4.8,
    storageTotalGb: 15,
    lastUploadAt: "2026-06-30T18:20:00.000Z",
    lastError: "Stream externo ainda nao configurado.",
  },
  tracks: radioTracksMock,
  categories: DEFAULT_CATEGORIES.map((name, index) => ({
    id: `category-${index + 1}`,
    name,
    color: index % 2 === 0 ? "#191970" : "#f59e0b",
    icon: "music",
    order: index + 1,
  })),
  playlists: radioPlaylistsMock,
  schedule: radioScheduleMock,
  listeners: radioListenersMock,
  logs: radioLogsMock,
  autoDj: DEFAULT_AUTODJ_SETTINGS,
};
