export const colors = Object.freeze({
  dark: {
    background: '#050505',
    backgroundSecondary: '#060606',
    surface: '#0b0c0d',
    surfaceAlt: '#111214',
    surfaceElevated: '#111214',
    hover: '#151515',
    border: '#2b2b2b',
    text: '#f5f5f5',
    textSecondary: '#a1a1aa',
    mutedText: '#a1a1aa',
    textMuted: '#71717a',
    primary: '#f0bf2f',
    primaryHover: '#ffd75a',
    primaryText: '#050505',
    success: '#16c47f',
    warning: '#f59e0b',
    danger: '#ff4444',
    info: '#38bdf8',
  },
  light: {
    background: '#f8fafc',
    backgroundSecondary: '#f1f5f9',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    surfaceElevated: '#f8fafc',
    hover: '#e2e8f0',
    border: '#cbd5e1',
    text: '#0f172a',
    textSecondary: '#475569',
    mutedText: '#475569',
    textMuted: '#64748b',
    primary: '#b7791f',
    primaryHover: '#975a16',
    primaryText: '#ffffff',
    success: '#15803d',
    warning: '#c2410c',
    danger: '#b91c1c',
    info: '#0369a1',
  },
})

export const semanticColors = Object.freeze({
  background: 'background',
  backgroundSecondary: 'backgroundSecondary',
  surface: 'surface',
  surfaceElevated: 'surfaceElevated',
  hover: 'hover',
  border: 'border',
  text: 'text',
  textSecondary: 'textSecondary',
  textMuted: 'textMuted',
  primary: 'primary',
  primaryHover: 'primaryHover',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
  info: 'info',
})
