export const colors = Object.freeze({
  dark: {
    background: '#010A26',
    backgroundSecondary: '#010A26',
    surface: '#021140',
    surfaceAlt: '#021A5C',
    surfaceElevated: '#021140',
    hover: '#03318C',
    border: 'rgba(5,108,242,.15)',
    glow: 'rgba(5,108,242,.30)',
    text: '#FFFFFF',
    textSecondary: '#AFC2FF',
    mutedText: '#AFC2FF',
    textMuted: '#7F9DFF',
    primary: '#03318C',
    primaryHover: '#056CF2',
    primaryText: '#FFFFFF',
    success: '#16c47f',
    warning: '#f59e0b',
    danger: '#ff4444',
    info: '#056CF2',
  },
  light: {
    background: '#eef4ff',
    backgroundSecondary: '#dbe8ff',
    surface: '#ffffff',
    surfaceAlt: '#f4f7ff',
    surfaceElevated: '#ffffff',
    hover: '#dbe8ff',
    border: 'rgba(5,108,242,.15)',
    glow: 'rgba(5,108,242,.30)',
    text: '#010A26',
    textSecondary: '#03318C',
    mutedText: '#03318C',
    textMuted: '#385aa8',
    primary: '#03318C',
    primaryHover: '#056CF2',
    primaryText: '#ffffff',
    success: '#15803d',
    warning: '#c2410c',
    danger: '#b91c1c',
    info: '#056CF2',
  },
})

export const semanticColors = Object.freeze({
  background: 'background',
  backgroundSecondary: 'backgroundSecondary',
  surface: 'surface',
  surfaceElevated: 'surfaceElevated',
  hover: 'hover',
  border: 'border',
  glow: 'glow',
  text: 'text',
  textSecondary: 'textSecondary',
  textMuted: 'textMuted',
  primary: 'primary',
  primaryHover: 'primaryHover',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
  info: 'info',
})
