import { Heart, Search, Shield } from 'lucide-react'
import { Badge, Button } from '../../../../design-system'
import { FootballEmptyState, FootballPanel } from './FootballCommon'
import { FootballMatchCard } from './FootballMatchCard'

export function FootballSearchResults({ query, teams, competitions, matches, favoriteKeys, onTeam, onFavoriteTeam, onOpen, onFavoriteMatch, onClear }) {
  if (!query) return null
  const total = teams.length + competitions.length + matches.length
  return (
    <FootballPanel title={`Resultados para “${query}”`} eyebrow={`${total} itens encontrados`} icon={Search} action={<Button variant="secondary" onClick={onClear}>Limpar busca</Button>}>
      {!total ? <FootballEmptyState title="Nenhum resultado encontrado" description="Tente outro time, competição ou confronto." actionLabel="Limpar filtros" onAction={onClear} /> : null}
      {teams.length ? <div className="mb-[var(--bds-space-32)]"><h3 className="mb-[var(--bds-space-16)] text-sm font-black uppercase tracking-[var(--bds-letter-overline)] text-[var(--bds-color-text-secondary)]">Times</h3><div className="grid gap-[var(--bds-space-16)] sm:grid-cols-2 xl:grid-cols-3">{teams.slice(0, 6).map((team) => { const favorited = favoriteKeys.has(`team:${team.id}`); return <div key={team.id} className="flex items-center gap-[var(--bds-space-16)] rounded-[var(--bds-radius-md)] border border-[var(--bds-color-border)] bg-[var(--bds-color-background)] p-[var(--bds-space-16)]"><button type="button" onClick={() => onTeam(team)} className="flex min-w-0 flex-1 items-center gap-[var(--bds-space-16)] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--bds-color-primary-hover)]">{team.crest ? <img src={team.crest} alt="" className="h-10 w-10 object-contain" /> : <Shield size={22} className="text-[var(--bds-color-primary-hover)]" aria-hidden="true" />}<span className="truncate font-black text-[var(--bds-color-text)]">{team.name}</span></button><button type="button" onClick={() => onFavoriteTeam(team)} aria-pressed={favorited} aria-label={favorited ? `Remover ${team.name} dos favoritos` : `Favoritar ${team.name}`} className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--bds-color-primary-hover)] ${favorited ? 'border-[var(--bds-color-primary-hover)] bg-[var(--bds-color-primary)] text-[var(--bds-color-text)]' : 'border-[var(--bds-color-border)] text-[var(--bds-color-text-secondary)]'}`}><Heart size={15} fill={favorited ? 'currentColor' : 'none'} aria-hidden="true" /></button></div> })}</div></div> : null}
      {competitions.length ? <div className="mb-[var(--bds-space-32)]"><h3 className="mb-[var(--bds-space-16)] text-sm font-black uppercase tracking-[var(--bds-letter-overline)] text-[var(--bds-color-text-secondary)]">Competições</h3><div className="flex flex-wrap gap-[var(--bds-space-8)]">{competitions.slice(0, 8).map((competition) => <Badge key={competition.id} className="border-[var(--bds-color-primary-hover)] bg-[color-mix(in_srgb,var(--bds-color-primary)_32%,transparent)] text-[var(--bds-color-text)]">{competition.name} · {competition.matches} jogos</Badge>)}</div></div> : null}
      {matches.length ? <div><h3 className="mb-[var(--bds-space-16)] text-sm font-black uppercase tracking-[var(--bds-letter-overline)] text-[var(--bds-color-text-secondary)]">Partidas</h3><div className="grid gap-[var(--bds-space-24)] 2xl:grid-cols-2">{matches.slice(0, 8).map((match) => <FootballMatchCard key={match.id} match={match} onOpen={onOpen} compact favorited={favoriteKeys.has(`match:${match.id}`)} onFavorite={onFavoriteMatch} />)}</div></div> : null}
    </FootballPanel>
  )
}
