import { radioConfig } from "../config/radioConfig.js";

export const radioDataStore = {
  config: {
    name: "Radio Bar dos Amigos",
    slogan: "A trilha sonora da nossa amizade",
    streamUrl: radioConfig.streamUrl,
    statusUrl: radioConfig.statusUrl,
    streamingType: radioConfig.provider,
    mountpoint: "",
    port: "",
    codec: "MP3",
    bitrate: "96 kbps",
    format: "audio/mpeg",
    autoReconnect: true,
    autoplay: false,
    defaultVolume: 70,
    primaryColor: "#191970",
    secondaryColor: "#f59e0b",
    theme: "dark",
    language: "pt-BR",
    autoDjEnabled: radioConfig.autoDjEnabled,
  },
  tracks: [
    {
      id: "track-1",
      title: "Noite dos Amigos",
      artist: "Banda do Bar",
      album: "Ao Vivo na Resenha",
      category: "Pagode",
      year: 2026,
      bitrate: "96 kbps",
      format: "MP3",
      size: "6.8 MB",
      duration: 218,
      uploadedAt: "2026-06-30T18:20:00.000Z",
      favorite: true,
      cover: "",
    },
    {
      id: "track-2",
      title: "Sertanejo da Galera",
      artist: "Arena Brasil",
      album: "Modao Premium",
      category: "Sertanejo",
      year: 2025,
      bitrate: "96 kbps",
      format: "MP3",
      size: "7.1 MB",
      duration: 241,
      uploadedAt: "2026-06-29T15:10:00.000Z",
      favorite: false,
      cover: "",
    },
    {
      id: "track-3",
      title: "Flashback do Bar",
      artist: "DJ Midnight",
      album: "Classicos",
      category: "Flashback",
      year: 1998,
      bitrate: "96 kbps",
      format: "MP3",
      size: "8.4 MB",
      duration: 266,
      uploadedAt: "2026-06-28T11:42:00.000Z",
      favorite: false,
      cover: "",
    },
  ],
  categories: [
    "Sertanejo",
    "Forro",
    "Arrocha",
    "Piseiro",
    "Pagode",
    "Pop",
    "Rock",
    "Flashback",
    "Internacional",
    "Anos 80",
    "Anos 90",
    "Anos 2000",
    "Eletronica",
    "Futebol",
    "Vinhetas",
    "Institucionais",
    "Hora Certa",
    "Comerciais",
  ].map((name, index) => ({
    id: `category-${index + 1}`,
    name,
    color: index % 2 === 0 ? "#191970" : "#f59e0b",
    icon: "music",
    order: index + 1,
  })),
  playlists: [
    { id: "playlist-1", name: "Manha Hits", trackIds: ["track-2", "track-1"], shuffle: true, repeat: false },
    { id: "playlist-2", name: "Noite dos Amigos", trackIds: ["track-1", "track-3"], shuffle: true, repeat: true },
  ],
  schedule: [
    { id: "schedule-1", day: "Segunda", start: "08:00", end: "10:00", title: "Sertanejo", playlistId: "playlist-1" },
    { id: "schedule-2", day: "Segunda", start: "10:00", end: "12:00", title: "Pagode", playlistId: "playlist-2" },
    { id: "schedule-3", day: "Sexta", start: "22:00", end: "23:59", title: "Flashback", playlistId: "playlist-2" },
  ],
  listeners: [
    { id: "listener-1", country: "Brasil", city: "Sao Paulo", system: "Android", browser: "Chrome", device: "Android" },
    { id: "listener-2", country: "Brasil", city: "Rio de Janeiro", system: "iOS", browser: "Safari", device: "iPhone" },
  ],
  logs: [
    { id: "log-1", type: "api", level: "info", message: "Radio API inicializada.", createdAt: new Date().toISOString() },
  ],
};
