export const competitionAdminEntities = {
  championships: {
    title: 'Campeonatos',
    description: 'Gerencie competicoes do Bar Competition Engine.',
    table: 'competitions',
    basePath: '/admin/competition/campeonatos',
    searchFields: ['name', 'slug', 'type'],
    filters: [{ key: 'status', label: 'Status', options: ['draft', 'published', 'archived', 'hidden'] }],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'slug', label: 'Slug' },
      { key: 'type', label: 'Tipo' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'name', label: 'Nome', required: true },
      { key: 'slug', label: 'Slug', required: true },
      { key: 'type', label: 'Tipo', type: 'select', options: ['football', 'basketball', 'volleyball', 'formula_1', 'ufc', 'esports', 'reality_show', 'custom'] },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived', 'hidden'] },
      { key: 'description', label: 'Descricao', type: 'textarea' },
    ],
  },
  seasons: {
    title: 'Temporadas',
    description: 'Cadastre temporadas vinculadas aos campeonatos.',
    table: 'competition_seasons',
    basePath: '/admin/competition/temporadas',
    searchFields: ['name', 'slug'],
    filters: [{ key: 'status', label: 'Status', options: ['draft', 'published', 'archived', 'hidden'] }],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'slug', label: 'Slug' },
      { key: 'competitionId', label: 'Campeonato' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'competitionId', label: 'ID do campeonato', required: true },
      { key: 'name', label: 'Nome', required: true },
      { key: 'slug', label: 'Slug', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived', 'hidden'] },
      { key: 'startsAt', label: 'Inicio', type: 'datetime-local' },
      { key: 'endsAt', label: 'Fim', type: 'datetime-local' },
    ],
  },
  rounds: {
    title: 'Rodadas',
    description: 'Organize rodadas por fase da competicao.',
    table: 'competition_rounds',
    basePath: '/admin/competition/rodadas',
    searchFields: ['name'],
    filters: [{ key: 'status', label: 'Status', options: ['draft', 'published', 'archived', 'hidden'] }],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'number', label: 'Numero' },
      { key: 'stageId', label: 'Fase' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'stageId', label: 'ID da fase', required: true },
      { key: 'name', label: 'Nome', required: true },
      { key: 'number', label: 'Numero', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived', 'hidden'] },
      { key: 'startsAt', label: 'Inicio', type: 'datetime-local' },
      { key: 'endsAt', label: 'Fim', type: 'datetime-local' },
    ],
  },
  teams: {
    title: 'Times',
    description: 'Gerencie participantes e times das competicoes.',
    table: 'competition_teams',
    basePath: '/admin/competition/times',
    searchFields: ['name', 'short_name'],
    filters: [{ key: 'status', label: 'Status', options: ['draft', 'published', 'archived', 'hidden'] }],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'shortName', label: 'Sigla' },
      { key: 'competitionId', label: 'Campeonato' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'competitionId', label: 'ID do campeonato' },
      { key: 'name', label: 'Nome', required: true },
      { key: 'shortName', label: 'Sigla' },
      { key: 'logoUrl', label: 'Logo URL' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived', 'hidden'] },
    ],
  },
  matches: {
    title: 'Jogos',
    description: 'Cadastre jogos e eventos competitivos.',
    table: 'competition_matches',
    basePath: '/admin/competition/jogos',
    searchFields: ['home_participant', 'away_participant'],
    filters: [{ key: 'status', label: 'Status', options: ['scheduled', 'open', 'live', 'finished', 'canceled', 'postponed'] }],
    columns: [
      { key: 'homeParticipant', label: 'Mandante' },
      { key: 'awayParticipant', label: 'Visitante' },
      { key: 'startsAt', label: 'Inicio' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'roundId', label: 'ID da rodada', required: true },
      { key: 'homeParticipant', label: 'Mandante' },
      { key: 'awayParticipant', label: 'Visitante' },
      { key: 'startsAt', label: 'Inicio', type: 'datetime-local', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'open', 'live', 'finished', 'canceled', 'postponed'] },
    ],
  },
}
